# run: conda env create --file environment.yml
name: religion
channels: 
- conda-forge
- defaults
dependencies:
- python==3.8
- pip
- pip:
  - notebook
  
  # - anaconda
# - pip
# - numpy==1.22.2
# - pip:
#   - matplotlib==2.0.0
